name = "TNG: DeepSeek R1T Chimera (free)"
release_date = "2025-04-27"
last_updated = "2025-04-27"
open_weights = false
tool_call = false
structured_output = false
temperature = true
reasoning = true
attachment = false

[modalities]
input = [ "text",]
output = [ "text",]

[limit]
context = 163840
input = 163840
output = 4096

[cost]
input = 0.0
output = 0.0
