name = "Cogito 32B"
family = "cogito"
release_date = "2025-05"
last_updated = "2025-05"
attachment = false
reasoning = true
tool_call = true
open_weights = true

[cost]
input = 2.07
output = 8.72
reasoning = 8.72

[limit]
context = 32_000
output = 32_000

[modalities]
input = ["text"]
output = ["text"]
