name = "OLMo 3 32B"
family = "allenai"
release_date = "2025-06"
last_updated = "2025-06"
attachment = false
reasoning = true
tool_call = false
open_weights = true

[cost]
input = 2.07
output = 8.72
reasoning = 8.72

[limit]
context = 65_536
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
