name = "Qwen3 VL 30B"
family = "qwen"
release_date = "2025-07"
last_updated = "2025-07"
attachment = true
reasoning = false
tool_call = true
open_weights = true

[cost]
input = 2.07
output = 8.72

[limit]
context = 250_000
output = 250_000

[modalities]
input = ["text", "image"]
output = ["text"]
