base_model = "deepseek/deepseek-v4-pro"
name = "Deepseek v4 Pro - Private"
reasoning = false
structured_output = false

[cost]
input = 1.5763
output = 5.5112

[limit]
context = 800_000
output = 380_000
