attachment = false
tool_call = true

[extends]
from = "mistral/mistral-large-latest"

[cost]
input = 0.5
output = 1.5
cache_read = 0.5
cache_write = 0.5

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
