name = "@cf/llava-hf/llava-1.5-7b-hf"
description = "LLaVA is an open-source chatbot trained by fine-tuning LLaMA/Vicuna on GPT-generated multimodal instruction-following data. It is an auto-regressive language model, based on the transformer architecture."
family = "llava"
release_date = "2024-05-01"
last_updated = "2024-05-01"
attachment = true
reasoning = false
temperature = false
tool_call = false
structured_output = false
open_weights = false

[limit]
context = 0
output = 0

[modalities]
input = ["image", "text"]
output = ["text"]
