name = "MiniMaxAI/MiniMax-M2.5"
description = "MiniMax-M2.5 is a SOTA large language model designed for real-world productivity. Trained in a diverse range of complex real-world digital working environments, M2.5 builds upon the coding expertise of M2.1..."
release_date = "2026-02-12"
last_updated = "2026-08-01"
attachment = false
reasoning = true
tool_call = true
structured_output = true
open_weights = false
reasoning_options = []

[cost]
input = 0.15
output = 1.15
cache_read = 0.03

[limit]
context = 196_608
output = 196_608

[modalities]
input = ["text"]
output = ["text"]
