base_model = "mistral/magistral-medium-latest"
name = "Magistral Medium 1.2"
description = "Magistral Medium 1.2 is Mistral AI's premier reasoning model for domain-specific, transparent, and multilingual reasoning."
structured_output = false
reasoning_options = []

[cost]
input = 2
output = 5
reasoning = 0
cache_read = 0
cache_write = 0

[limit]
context = 40_000
output = 40_000
