name = "Qwen3 Coder Next FP8 1M"
family = "qwen"
release_date = "2026-05"
last_updated = "2026-05-12"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = true

[cost]
input = 0.0
output = 0.0

[limit]
context = 1024000
output = 8192

[modalities]
input = ["text"]
output = ["text"]
