base_model = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning"
temperature = true
tool_call = true
attachment = true
reasoning_options = []
reasoning = true
name = "Nemotron 3 Nano Omni (free)"
structured_output = false

[cost]
input = 0
output = 0
