base_model = "openai/gpt-4o"
last_updated = "2024-05-13"
tool_call = false
structured_output = false

[cost]
input = 2.499
output = 9.996

[limit]
context = 128000
input = 128000
output = 16384

[modalities]
input = [ "text", "image" ]
output = [ "text" ]

