name = "seed-1-6-250915"
description = "Seed 1.6 is a general-purpose model released by the ByteDance Seed team. It incorporates multimodal capabilities and adaptive deep thinking with a 256K context window."
release_date = "2025-12-23"
last_updated = "2026-08-01"
attachment = true
reasoning = true
tool_call = true
structured_output = true
open_weights = true
reasoning_options = []

[cost]
input = 0.25
output = 2

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text", "image", "video"]
output = ["text"]
