name = "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)"
release_date = "2025-11-20"
last_updated = "2025-11-20"
attachment = true
reasoning = false
temperature = true
tool_call = false
open_weights = false

[cost]
input = 2
output = 12

[limit]
context = 64000
output = 32000

[modalities]
input = ["image", "text"]
output = ["text"]
