name = "Qwen-VL Plus"
family = "qwen"
release_date = "2024-01-25"
last_updated = "2025-08-15"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
knowledge = "2024-04"
open_weights = false

[cost]
input = 0.115
output = 0.287
cache_read = 0.023

[limit]
context = 131_072
output = 8_192

[modalities]
input = ["text", "image", "video", "pdf"]
output = ["text"]
