name = "Qwen3-Coder 480B-A35B Instruct"
family = "qwen"
release_date = "2025-04"
last_updated = "2025-04"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = false
knowledge = "2025-04"
open_weights = true

[cost]
input = 0.861
output = 3.441

[[cost.tiers]]
tier = { type = "context", size = 32_000 }
input = 1.291
output = 5.161

[[cost.tiers]]
tier = { type = "context", size = 128_000 }
input = 2.151
output = 8.602

[[cost.tiers]]
tier = { type = "context", size = 256_000 }
input = 4.301
output = 43.006

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
