name = "Doubao-Seedream-5.0-pro"
description = "Seedream-5.0-pro is ByteDance’s latest image generation model, advancing image creation into a new stage of controllable production. This update brings more controllable editing, more production-ready workflows, and more natural visual results."
release_date = "2026-07-09"
last_updated = "2026-07-09"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = false

[limit]
context = 100_000
output = 0

[modalities]
input = ["text", "image"]
output = ["image"]
