base_model = "mistral/magistral-medium-latest"
name = "Magistral Medium 2509"
attachment = true
reasoning_options = []

[cost]
input = 2.1
output = 5.25

[limit]
output = 64_000

[modalities]
input = ["text", "image"]
