import { lstatSync, readdirSync } from "node:fs";
import path from "node:path";
import { z } from "zod";

import { MissingReasoningOptionsError } from "../missing-reasoning-options.js";
import type { ExistingModel, SyncProvider, SyncedFullModel, SyncedModel } from "../index.js";
import { factorBaseModel } from "./openrouter.js";

const API_ENDPOINT = "https://api.gpuflow.ai/v1/models";
const MODELS_DIR = path.join(import.meta.dirname, "..", "..", "..", "..", "..", "models");

/**
 * GPU Flow public catalog (`/v1/models`, OpenRouter 2.4 provider document).
 * The document is generated by the GPU Flow inference gateway from its
 * production whitelist, so the sync always reflects the serving state:
 * pricing (USD per token), context/output limits, modalities, published
 * features (tools / structured outputs / reasoning), `is_ready` (GA vs
 * internal-only) and identity (Hugging Face id, OpenRouter slug).
 */

const PricingEntry = z.object({
  type: z.string(),
  unit: z.string().optional(),
  cost_usd: z.string(),
});

const SupportedInputs = z.object({
  max_context_length: z.object({ value: z.number(), unit: z.string() }).passthrough(),
});

const InputModality = z.union([
  z.object({
    type: z.literal("text"),
    supported_inputs: SupportedInputs,
    pricing: z.array(PricingEntry).default([]),
  }),
  z.object({ type: z.string() }).passthrough(),
]);

const OutputModality = z.object({
  type: z.string(),
  max_length: z.object({ value: z.number(), unit: z.string() }).optional(),
  streaming: z.boolean().optional(),
  supported_parameters: z.record(z.string(), z.unknown()).default({}),
  pricing: z.array(PricingEntry).default([]),
});

const GpuflowCatalogModel = z.object({
  schema_version: z.string().optional(),
  id: z.string(),
  name: z.string(),
  created: z.number(),
  description: z.string().optional(),
  hugging_face_id: z.string().optional(),
  openrouter: z.object({ slug: z.string().optional() }).passthrough().optional(),
  quantization: z.string().optional(),
  is_ready: z.boolean().default(false),
  compliance: z.record(z.string(), z.unknown()).optional(),
  datacenters: z.array(z.object({ country_code: z.string().optional() }).passthrough()).optional(),
  input_modalities: z.array(InputModality),
  output_modalities: z.array(OutputModality),
});

const GpuflowCatalog = z.object({
  data: z.array(GpuflowCatalogModel),
});

export type GpuflowCatalogModel = z.infer<typeof GpuflowCatalogModel>;

/**
 * OpenRouter vendor / Hugging Face organization -> canonical lab directory
 * under models/. Used only for NEW models; existing base_model declarations
 * always win (preserveBaseModel), so hand-curated resolutions are stable.
 *
 * Every entry below is backed by a live row of the GPU Flow catalog
 * (https://api.gpuflow.ai/v1/models, verified 2026-09-23):
 *   - openrouter.slug: "z-ai/glm-5.3", "qwen/*", "deepseek/*",
 *     "nvidia/nemotron-3.5-lightning", "google/gemma-4-26b-a4b-it"
 *   - hugging_face_id: "RadixArk/GLM-5.3-NVFP4", "Qwen/*",
 *     "Inferact/Qwen3.8-27B-NVFP4", "RedHatAI/Qwen3-VL-32B-Instruct-NVFP4",
 *     "deepseek-ai/*", "nvidia/*", "BSC-LT/ALIA-40b-instruct-2606"
 * Unverified vendors are deliberately absent so future models cannot
 * mis-resolve; they fail closed for manual authoring instead.
 */
const CANONICAL_PREFIXES: Record<string, string> = {
  // OpenRouter vendor prefixes (from the `openrouter.slug` field)
  "z-ai": "zhipuai",
  qwen: "alibaba",
  deepseek: "deepseek",
  nvidia: "nvidia",
  google: "google",
  // Hugging Face organization prefixes (from the `hugging_face_id` field)
  "deepseek-ai": "deepseek",
  Qwen: "alibaba",
  RedHatAI: "alibaba",
  Inferact: "alibaba",
  RadixArk: "zhipuai",
  "BSC-LT": "bsc-lt",
};

type SupportedModality = "text" | "audio" | "image" | "video" | "pdf";

const MODALITY_MAP: Record<string, SupportedModality | undefined> = {
  text: "text",
  audio: "audio",
  image: "image",
  video: "video",
  pdf: "pdf",
};

interface MetadataIndexEntry {
  id: string;
  file: string;
  lower: string;
}

let metadataIndex: MetadataIndexEntry[] | undefined;

function metadataEntries(): MetadataIndexEntry[] {
  if (metadataIndex !== undefined) return metadataIndex;
  metadataIndex = [];
  try {
    for (const namespace of readdirSync(MODELS_DIR)) {
      const dir = path.join(MODELS_DIR, namespace);
      if (!lstatSync(dir).isDirectory()) continue;
      for (const file of readdirSync(dir)) {
        if (!file.endsWith(".toml")) continue;
        metadataIndex.push({
          id: `${namespace}/${file.slice(0, -5)}`,
          file: `${namespace}/${file.slice(0, -5)}`,
          lower: file.slice(0, -5).toLowerCase(),
        });
      }
    }
  } catch {
    // Missing models/ dir -> no canonical resolution, full models emitted.
  }
  return metadataIndex;
}

/**
 * Resolve the canonical lab model for a NEW GPU Flow model. Best effort:
 * tries the OpenRouter slug first (the marketplace already normalizes
 * vendor/model naming), then the Hugging Face id with light normalization
 * (strip NVIDIA prefix, quantization suffixes, release-date suffixes).
 */
function resolveCanonical(model: GpuflowCatalogModel): string | undefined {
  const candidates: Array<{ namespace: string; modelID: string }> = [];
  const slug = model.openrouter?.slug;
  if (slug !== undefined) {
    const [vendor, ...rest] = slug.split(":")[0].split("/");
    const namespace = CANONICAL_PREFIXES[vendor];
    if (namespace !== undefined && rest.length > 0) {
      candidates.push({ namespace, modelID: rest.join("/") });
    }
  }
  const hf = model.hugging_face_id;
  if (hf !== undefined) {
    const [org, ...rest] = hf.split("/");
    const namespace = CANONICAL_PREFIXES[org];
    if (namespace !== undefined && rest.length > 0) {
      candidates.push({ namespace, modelID: rest.join("/") });
    }
  }

  const entries = metadataEntries();
  for (const { namespace, modelID } of candidates) {
    const normalized = normalizeModelID(namespace, modelID);
    const direct = entries.find((e) => e.id === `${namespace}/${normalized}`);
    if (direct !== undefined) return direct.id;
    const lower = entries.find(
      (e) => e.id.startsWith(`${namespace}/`) && e.lower === normalized.toLowerCase(),
    );
    if (lower !== undefined) return lower.id;
  }
  return undefined;
}

function normalizeModelID(namespace: string, modelID: string): string {
  let id = modelID;
  if (namespace === "nvidia") {
    id = id
      .replace(/^NVIDIA-/, "")
      .replace(/^nvidia-/, "")
      .replace(/-NVFP4(-QAD)?$/i, "")
      .replace(/-BF16$/i, "");
  }
  return id
    .replace(/-(?:fp8|nvfp4|bf16)$/i, "")
    .replace(/-(\d{4})$/, "");
}

function costFromUsdPerToken(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const perMillion = Number(value) * 1_000_000;
  if (!Number.isFinite(perMillion)) return undefined;
  return Math.round(perMillion * 1e6) / 1e6;
}

function priceOf(pricing: Array<{ type: string; cost_usd: string }>, type: string): number | undefined {
  return costFromUsdPerToken(pricing.find((entry) => entry.type === type)?.cost_usd);
}

function inputModality(model: GpuflowCatalogModel, type: string) {
  return model.input_modalities.find((m) => m.type === type);
}

function inputModalities(model: GpuflowCatalogModel): SupportedModality[] {
  const normalized = model.input_modalities
    .map((m) => MODALITY_MAP[m.type] ?? (m.type as SupportedModality))
    .filter((value) => value !== undefined);
  return [...new Set(normalized)];
}

function outputModalities(model: GpuflowCatalogModel): SupportedModality[] {
  const normalized = model.output_modalities
    .map((m) => MODALITY_MAP[m.type] ?? (m.type as SupportedModality))
    .filter((value) => value !== undefined);
  return [...new Set(normalized)];
}

function hasParameter(model: GpuflowCatalogModel, name: string): boolean {
  return model.output_modalities.some(
    (m) => m.supported_parameters !== undefined && name in m.supported_parameters,
  );
}

/** GA text/vision chat model — the only rows models.dev should track. */
function inScope(model: GpuflowCatalogModel): boolean {
  return model.is_ready && model.input_modalities.some((m) => m.type === "text");
}

export const gpuflow = {
  id: "gpuflow",
  name: "GPU Flow",
  modelsDir: "providers/gpuflow/models",
  // The catalog is NOT lifecycle-authoritative: a vanished model (or a
  // truncated /v1/models fetch) must never delete published entries.
  // Removals are human decisions, like openai/ollama-cloud/merge-gateway.
  deleteMissing: false,
  // In-scope = GA text/vision chat model. Internal-only deployments
  // (is_ready=false) and audio/music/pooling rows are skipped silently:
  // no missing-model issues are opened for them.
  sourceID(model) {
    return inScope(model) ? model.id : undefined;
  },
  missingModelID(model) {
    return inScope(model) ? model.id : undefined;
  },
  async fetchModels() {
    const response = await fetch(API_ENDPOINT);
    if (!response.ok) {
      throw new Error(`GPU Flow catalog request failed: ${response.status} ${response.statusText}`);
    }
    return response.json();
  },
  parseModels(raw) {
    return GpuflowCatalog.parse(raw).data;
  },
  translateModel(model, context) {
    // Internal-only models never reach models.dev.
    if (!model.is_ready) return undefined;

    const existing = context.existing(model.id);
    const baseModel = existing?.base_model ?? resolveCanonical(model);

    const textInput = inputModality(model, "text");
    if (textInput === undefined) {
      return undefined; // audio/music/pooling endpoints are out of scope
    }
    const limit = {
      context:
        textInput.supported_inputs.max_context_length?.value ?? existing?.limit?.context ?? 0,
      output: model.output_modalities[0]?.max_length?.value ?? existing?.limit?.output ?? 0,
    };
    const reasoning = hasParameter(model, "reasoning");
    // Fail closed: the catalog publishes the reasoning CAPABILITY but not
    // the wire CONTROLS (effort levels, toggles, thinking budgets). Those
    // are hand-documented per model from the gateway. A reasoner without
    // hand-authored reasoning_options must never sync as [] ("no caller
    // control" would be fabricated) — it is reported and left for a human.
    if (reasoning && existing?.reasoning_options === undefined) {
      throw new MissingReasoningOptionsError(
        model.id,
        "GPU Flow's catalog publishes the reasoning capability but not the wire controls; " +
          "hand-author reasoning_options (reasoning.effort levels / budget per the gateway) " +
          "in providers/gpuflow/models before syncing this model",
      );
    }
    const modalities = {
      input: inputModalities(model),
      output: outputModalities(model),
    };
    const cost = {
      input: priceOf("pricing" in textInput ? textInput.pricing ?? [] : [], "prompt"),
      cache_read: priceOf("pricing" in textInput ? textInput.pricing ?? [] : [], "cached_prompt"),
      output: priceOf(model.output_modalities[0]?.pricing ?? [], "completion"),
    };

    const synced: SyncedFullModel = {
      name: model.name,
      attachment: modalities.input.some((m) => m !== "text"),
      reasoning,
      // The catalog publishes the capability, not the wire controls; the
      // per-model reasoning_options (effort levels, toggles, budgets) are
      // hand-documented from the gateway and preserved from the existing
      // file on every sync.
      reasoning_options: reasoning ? existing?.reasoning_options : undefined,
      temperature: hasParameter(model, "temperature") ? true : undefined,
      tool_call: hasParameter(model, "tools"),
      // Always a boolean: `false` is a real delta when the lab entry declares
      // structured output but this host does not publish json_mode.
      structured_output: hasParameter(model, "structured_outputs"),
      // Manual lifecycle state (alpha/beta) is never touched by the sync.
      status: existing?.status,
      interleaved: existing?.interleaved,
      cost:
        cost.input !== undefined || cost.output !== undefined
          ? {
              input: cost.input,
              output: cost.output,
              cache_read: cost.cache_read !== undefined && cost.cache_read > 0
                ? cost.cache_read
                : undefined,
            }
          : undefined,
      limit,
      modalities,
    };

    if (baseModel !== undefined) {
      const factored = factorBaseModel(baseModel, synced, limit, existing?.base_model_omit);
      return {
        id: model.id,
        model: factored,
        header: [
          `# ${model.name} served by GPU Flow (${model.quantization ?? "open weights"}) on NVIDIA B200 in Madrid.`,
          `# Catalog and pricing: ${API_ENDPOINT} (hourly sync)`,
        ].join("\n"),
      };
    }

    // No canonical lab resolves AND no hand-authored file exists: fail
    // closed. Never auto-generate lab stubs (bare provider IDs as metadata
    // namespaces, generic descriptions, catalog `created` as release
    // dates) — a human authors the base_model/lab pair and the next sync
    // run picks it up. missingModelID already reports the skipped ID.
    if (existing === undefined) {
      return undefined;
    }

    // Hand-authored full model (no base_model by deliberate choice, e.g.
    // a lab entry with its own models/ file authored by a human): sync
    // only the catalog-owned fields; everything else is preserved.
    return {
      id: model.id,
      model: {
        ...synced,
        description: existing.description,
        release_date: existing.release_date,
        last_updated: existing.last_updated,
        open_weights: existing.open_weights,
        knowledge: existing.knowledge,
      },
    };
  },
} satisfies SyncProvider<GpuflowCatalogModel>;
