import type { SyncedModel } from "../index.js";

type ReasoningOptions = NonNullable<SyncedModel["reasoning_options"]>;

export type NearAICuration = {
  source: string[];
  reasoning_options?: ReasoningOptions;
  interleaved?: { field: string };
  base_model?: string;
  modalities?: { input: string[] };
  attachment?: boolean;
  skip?: true;
};

export const nearaiCuration: Record<string, NearAICuration> = {
  "Qwen/Qwen3.8-27B": {
    source: [
      "Toggle: chat_template_kwargs.enable_thinking = true|false (on by default)",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-08:",
      "reasoning_content present when on, absent when off",
      "Text and image, as /v1/models reports for this route. The lab entry adds video,",
      "which was never probed here.",
    ],
    reasoning_options: [{ type: "toggle" }],
    interleaved: { field: "reasoning_content" },
    modalities: { input: ["text", "image"] },
  },
  "anthropic/claude-fable-5": {
    source: [
      "No caller-side reasoning control on this route: every control is rejected or inert.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      'thinking.type = "enabled" and reasoning_effort are both rejected outright.',
      "reasoning.effort is accepted but is a proven no-op: six samples gave completion_tokens",
      "of 473/438/389/434/398/356 with no parameter against 470/352/350/319/360/441 at low,",
      "fully overlapping. At three samples the two looked separated; the gap dissolved at six.",
      "No reply carries reasoning_content.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "anthropic/claude-fable-5-1": {
    source: [
      "No caller-side reasoning control on this route: every control is rejected or inert.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      'thinking.type = "enabled" and reasoning_effort are both rejected outright.',
      "reasoning.effort is accepted but is a proven no-op: three samples gave completion_tokens",
      "of 334/330/246 with no parameter against 253/254/208 at low and 310/265/187 at max,",
      "every range overlapping. No reply carries reasoning_content.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "anthropic/claude-opus-4-8": {
    source: [
      "No caller-side reasoning control on this route: every control is rejected or inert.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      'thinking.type = "enabled" and reasoning_effort are both rejected outright.',
      "reasoning.effort is accepted but is a proven no-op: six samples gave completion_tokens",
      "of 492/467/523/473/551/500 with no parameter against 443/476/510/450/495/431 at low,",
      "overlapping. At three samples the two looked separated; the gap dissolved at six.",
      "No reply carries reasoning_content.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "anthropic/claude-opus-5": {
    source: [
      "No caller-side reasoning control on this route: every control is rejected or inert.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      'thinking.type = "enabled" is rejected with "thinking.type.enabled" is not supported',
      "for this model, and reasoning_effort with reasoning_effort: Extra inputs are not permitted.",
      "reasoning.effort is accepted but is a proven no-op: three samples per level gave",
      "completion_tokens of 708/700/686 with no parameter against 547/772/683 at low,",
      "663/565/718 at medium, 757/650/651 at high and 641/597/700 at max, every range",
      "overlapping the no-parameter range. No reply carries reasoning_content.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "anthropic/claude-sonnet-5": {
    source: [
      "No caller-side reasoning control on this route: every control is rejected or inert.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      'thinking.type = "enabled" and reasoning_effort are both rejected outright.',
      "reasoning.effort is accepted but is a proven no-op: three samples gave completion_tokens",
      "of 887/681/861 with no parameter against 929/598/758 at low and 846/878/744 at max,",
      "every range overlapping. No reply carries reasoning_content.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "deepseek-ai/DeepSeek-V4-Flash": {
    source: [
      "Toggle: chat_template_kwargs.thinking = true|false (OFF by default on this host)",
      "Effort: reasoning_effort = high|max, the documented DeepSeek V4 baseline",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      "With no reasoning_effort usage.reasoning_tokens was 0, so effort also turns reasoning on.",
      "Six samples per level at temperature 0 gave low 681/749/2598/1117/1032/560,",
      "medium 1567/841/889/1160/790/867, high 237/370/420/316/385/229 and",
      "max 857/957/782/1582/532/490. Only high is cleanly separated; low, medium and max",
      "overlap each other, so there is no host evidence that low or medium is a distinct",
      "level and the lab's documented low/medium -> high mapping stands. An earlier reading",
      "of three samples suggested medium was distinct; six samples dissolved it.",
      "Serves the bare Flash weights, not the 0731 build: prod/DeepSeek-V4-Flash-SGL-FP4-TP2x2.yaml",
      "passes --model-path deepseek-ai/DeepSeek-V4-Flash, and the endpoint reports max_model_len 1048576.",
    ],
    base_model: "deepseek/deepseek-v4-flash",
    reasoning_options: [{ type: "toggle" }, { type: "effort", values: ["high", "max"] }],
    interleaved: { field: "reasoning_content" },
  },
  "deepseek/deepseek-v3.2": {
    source: [
      "Toggle: chat_template_kwargs.thinking = true|false (OFF by default on this host)",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-08:",
      "reasoning_content present when on, absent when off",
    ],
    reasoning_options: [{ type: "toggle" }],
    interleaved: { field: "reasoning_content" },
  },
  "moonshotai/kimi-k2.6": {
    source: [
      "Toggle: chat_template_kwargs.thinking = true|false (on by default)",
      "Effort is not a control here, unlike the sibling kimi-k3 route.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions, toggle 2026-09-08",
      "and effort 2026-09-11 with six samples per level at temperature 0.",
      "reasoning_tokens: no parameter 535/934/740/1027/815, low 870/686/720/672/928 and",
      "high 627/707/832/714/873 all overlap heavily, so neither level changes anything.",
      "reasoning_effort = max is refused outright: six long attempts and three short control",
      "attempts all failed while no parameter, low and high each succeeded three times.",
      'The gateway reports that refusal as "The model is currently unavailable", which is a',
      "misleading message for a rejected parameter value.",
      "Text only, although /v1/models advertises image input: on 2026-09-10 a two-colour",
      "test image was misread, while the same prompt without it said it could not see images.",
    ],
    reasoning_options: [{ type: "toggle" }],
    interleaved: { field: "reasoning_content" },
    modalities: { input: ["text"] },
    attachment: false,
  },
  "moonshotai/kimi-k3": {
    source: [
      "Toggle: chat_template_kwargs.thinking = true|false (on by default)",
      "Effort: reasoning_effort = low|high|max is also honoured",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions, toggle 2026-09-08",
      "and effort 2026-09-11 with six samples per level at temperature 0.",
      "reasoning_tokens: no parameter 168/162/168/178/162/168, low 181/180/245/158/180/220,",
      "high 271/280/245/216/217/245, max 163/166/166/162/166/168. high sits above the",
      "no-parameter range with no overlap, so effort is honoured; low spans the baseline and",
      "max is indistinguishable from it, so no ordering is claimed.",
      "Text only, although /v1/models advertises image input: on 2026-09-10 a two-colour",
      "test image was misread, while the same prompt without it said it could not see images.",
    ],
    reasoning_options: [{ type: "toggle" }, { type: "effort", values: ["low", "high", "max"] }],
    interleaved: { field: "reasoning_content" },
    modalities: { input: ["text"] },
    attachment: false,
  },
  "openai/gpt-5.6-luna": {
    source: [
      "Relayed to OpenAI; reasoning_effort passes through (https://docs.near.ai/cloud/reasoning-models).",
      "Levels as OpenAI's own entry, providers/openai/models/gpt-5.6-luna.toml, which is how",
      "every NEAR AI GPT-5 route is authored since anomalyco/models.dev#2313.",
      "Flat pricing is deliberate: https://cloud-api.near.ai/v1/models publishes a single rate",
      "per model and exposes no tier structure for any of them, so a context tier cannot be",
      "derived from the host. The tiers on gpt-5.4 and gpt-5.5 were hand-authored, not synced.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [
      { type: "effort", values: ["none", "low", "medium", "high", "xhigh", "max"] },
    ],
    modalities: { input: ["text", "image"] },
  },
  "openai/gpt-5.6-sol": {
    source: [
      "Relayed to OpenAI; reasoning_effort passes through (https://docs.near.ai/cloud/reasoning-models).",
      "Levels as OpenAI's own entry, providers/openai/models/gpt-5.6-sol.toml, which is how",
      "every NEAR AI GPT-5 route is authored since anomalyco/models.dev#2313.",
      "Flat pricing is deliberate: https://cloud-api.near.ai/v1/models publishes a single rate",
      "per model and exposes no tier structure for any of them, so a context tier cannot be",
      "derived from the host. The tiers on gpt-5.4 and gpt-5.5 were hand-authored, not synced.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [
      { type: "effort", values: ["none", "low", "medium", "high", "xhigh", "max"] },
    ],
    modalities: { input: ["text", "image"] },
  },
  "openai/gpt-6-astra": {
    source: [
      "Relayed to OpenAI; reasoning_effort passes through (https://docs.near.ai/cloud/reasoning-models).",
      "Levels as OpenAI's own entry, providers/openai/models/gpt-6-astra.toml, which is how",
      "every NEAR AI GPT-5 route is authored since anomalyco/models.dev#2313.",
      "Flat pricing is deliberate: https://cloud-api.near.ai/v1/models publishes a single rate",
      "per model and exposes no tier structure for any of them, so a context tier cannot be",
      "derived from the host. The tiers on gpt-5.4 and gpt-5.5 were hand-authored, not synced.",
      'Text and image only: the lab entry adds pdf, and a type: "file" content part fails',
      "schema deserialisation on every route.",
    ],
    reasoning_options: [{ type: "effort", values: ["low", "medium", "high", "xhigh", "max"] }],
    modalities: { input: ["text", "image"] },
  },
  "openai/privacy-filter": {
    source: [
      "PII detection by token classification, priced per input token with no output price.",
      "Not a chat model, and models.dev's token-cost schema has no way to describe it.",
    ],
    skip: true,
  },
  "qwen/qwen3-32b": {
    source: [
      "Being decommissioned, so it is deliberately not published to models.dev.",
      'It is also unreachable in the meantime: every request returns "The model is',
      'currently unavailable", 6 attempts across two sessions a day apart, 2026-09-10',
      "and 2026-09-11. Remove this entry once the route drops off /v1/models.",
    ],
    skip: true,
  },
  "qwen/qwen3.5-397b-a17b": {
    source: [
      "Toggle: chat_template_kwargs.enable_thinking = true|false (on by default)",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-08:",
      "reasoning_content present when on, absent when off",
      "Accepts images, although /v1/models lists text only: on 2026-09-10 a two-colour test",
      "image was read correctly, while the same prompt without it guessed wrong.",
    ],
    reasoning_options: [{ type: "toggle" }],
    interleaved: { field: "reasoning_content" },
    modalities: { input: ["text", "image"] },
  },
  "qwen/qwen3.7-max": {
    source: [
      "No caller-side reasoning control on this route: reasoning_content is never returned.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-08 with",
      "chat_template_kwargs.enable_thinking, chat_template_kwargs.thinking, reasoning_effort,",
      "reasoning.enabled and reasoning.effort; reasoning_content was empty in every case.",
    ],
    reasoning_options: [],
  },
  "google/gemini-3.8-flash": {
    source: [
      "No caller-side reasoning control on this route: effort is accepted and is a no-op.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11.",
      "reasoning_effort and reasoning.effort are both accepted (HTTP 200) and no reply",
      "carries reasoning_content. Three samples per level at temperature 0 gave",
      "completion_tokens of 330/383/402 with no parameter, 356/309/358 at low,",
      "340/304/310 at medium and 386/376/409 at high: the no-parameter spread is wider",
      "than any gap between levels, so the values change nothing.",
      "Text and image only, although the lab entry also lists video, audio and pdf: on",
      "2026-09-11 a two-colour test image was read correctly while the same prompt without",
      'it guessed wrong, and a type: "file" part fails schema deserialisation on every route.',
    ],
    reasoning_options: [],
    modalities: { input: ["text", "image"] },
  },
  "x-ai/grok-4.6": {
    source: [
      "Effort: reasoning_effort = low|medium|high|xhigh. The route never returns",
      "reasoning_content, so the control was measured by reply length instead.",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions 2026-09-11,",
      "three samples per level at temperature 0, completion_tokens: no parameter",
      "1023/1211/994, low 623/513/731, medium 1180/1081/1379, high 1260/1108/1218,",
      "xhigh 1184/1486/1377. low is clearly distinct, overlapping no other level;",
      "medium, high and xhigh are accepted but overlap each other, so only the set of",
      "accepted levels is claimed, never an ordering.",
      "Text only, although the lab entry lists image: the same request carrying an image_url",
      'part failed twice with "Provider returned error" while the text-only control succeeded.',
    ],
    reasoning_options: [{ type: "effort", values: ["low", "medium", "high", "xhigh"] }],
    modalities: { input: ["text"] },
    attachment: false,
  },
  "z-ai/glm-5.3-flash": {
    source: [
      "Toggle: chat_template_kwargs.enable_thinking = true|false (on by default)",
      "Effort: reasoning_effort = low|high|max is also honoured, and sharply",
      "Verified live on POST https://cloud-api.near.ai/v1/chat/completions, toggle 2026-09-08",
      "and effort 2026-09-11 with three samples per level at temperature 0.",
      "reasoning_tokens: no parameter 394/389/389, low 9/9/9, high 25/25/25, max 402/437/424.",
      "Every level is deterministic and cleanly separated, so this route genuinely grades.",
      "Note low and high both suppress reasoning far below the default, so the levels are",
      "not ordered by cost and no ordering is claimed.",
      "Text and image, as /v1/models reports for this route. The lab entry adds video,",
      'which was never probed here, and pdf, which fails as a type: "file" content part',
      "on every route.",
    ],
    reasoning_options: [{ type: "toggle" }, { type: "effort", values: ["low", "high", "max"] }],
    interleaved: { field: "reasoning_content" },
    modalities: { input: ["text", "image"] },
  },
  "zai-org/GLM-5.1-FP8": {
    source: [
      "Retired on 2026-09-11, when its completion endpoint was removed from production",
      "monitoring and its alert rules were paused. Absent from /v1/models since the same",
      "day. Recorded here so the removal reads as deliberate rather than a gap.",
    ],
    skip: true,
  },
};
