base_model = "deepseek/deepseek-v4-flash"
name = "DeepSeek-V4-Flash-EL"
attachment = true
reasoning_options = [{ type = "toggle" }, { type = "budget_tokens", min = 1, max = 393_216 }]

[cost]
input = 0.1394
output = 0.2778

[limit]
input = 1_000_000

[modalities]
input = ["text", "pdf"]
