base_model = "alibaba/qwen3.6-max-preview"
name = "Qwen3.6-Max-Preview"
attachment = true
reasoning_options = [{ type = "toggle" }, { type = "budget_tokens", min = 1, max = 32_768 }]

[cost]
input = 1.3131
output = 7.8788

[[cost.tiers]]
tier = { type = "context", size = 128_000 }
input = 1.96965
output = 11.8182

[limit]
context = 256_000

[modalities]
input = ["text", "pdf"]
