name = "DeepSeek R1-0528"
family = "deepseek"
attachment = false
reasoning = true
tool_call = undefined
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = undefined

[cost]
input = 0.03
output = 0.07

[limit]
context = 163_840
output = 163_840

[modalities]
input = ["text"]
output = ["text"]
