name = "Qwen: Qwen3 VL 8B Instruct"
release_date = "2025-10-14"
last_updated = "2025-10-14"
open_weights = false
tool_call = true
structured_output = true
temperature = true
reasoning = true
attachment = true

[modalities]
input = [ "image", "text",]
output = [ "text",]

[limit]
context = 131072
input = 131072
output = 32768

[cost]
input = 0.064
output = 0.39999999999999997
