name = "@cf/nvidia/nemotron-3-120b-a12b"
description = "Nemotron model for efficient reasoning, coding, and specialized AI agents"
release_date = "2026-06-22"
last_updated = "2026-08-01"
attachment = false
reasoning = true
tool_call = true
structured_output = false
open_weights = false
reasoning_options = []

[cost]
input = 0.5
output = 1.5

[limit]
context = 256_000
output = 256_000

[modalities]
input = ["text"]
output = ["text"]
