name = "codestral-2508"
description = "Mistral's cutting-edge language model for coding released end of July 2025. Codestral specializes in low-latency, high-frequency tasks such as fill-in-the-middle (FIM), code correction and test generation. [Blog Post](https://mistral.ai/news/codestral-25-08)"
release_date = "2025-08-01"
last_updated = "2026-08-01"
attachment = true
reasoning = false
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.3
output = 0.9
cache_read = 0.03

[limit]
context = 256_000
output = 256_000

[modalities]
input = ["text", "pdf"]
output = ["text"]
