base_model = "mistral/magistral-medium-latest"
release_date = "2026-01-06"
last_updated = "2026-08-01"
attachment = true
structured_output = true
open_weights = true
reasoning_options = []

[cost]
input = 2
output = 5

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text", "image"]
