name = "Meta: Llama 3.1 405B (base) (OpenRouter)"
family = "llama"
attachment = false
reasoning = false
tool_call = false
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = false

[cost]
input = 4
output = 4

[limit]
context = 128_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
