name = "Inflection: Inflection 3 Pi"
release_date = "2024-10-10"
last_updated = "2024-10-10"
open_weights = false
tool_call = false
structured_output = false
temperature = true
reasoning = false
attachment = false

[modalities]
input = [ "text",]
output = [ "text",]

[limit]
context = 8000
input = 8000
output = 1024

[cost]
input = 2.5
output = 10.0
