base_model = "alibaba/qwen-plus"
name = "Qwen Plus (2025-12-01)"
tool_call = false
structured_output = false
release_date = "2025-12-01"
last_updated = "2025-12-01"

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"
min = 1
max = 81_920

[cost]
input = 0.4
output = 1.2
reasoning = 4

[[cost.tiers]]
tier = { size = 256_000 }
input = 1.2
output = 3.6
reasoning = 12
