base_model = "alibaba/qwen3-vl-flash"

[cost]
input = 0.022
output = 0.215
cache_read = 0.005
cache_write = 0.005

[[cost.tiers]]
tier = { size = 32_768 }
input = 0.043
output = 0.43
cache_read = 0.009
cache_write = 0.009

[[cost.tiers]]
tier = { size = 128_000 }
input = 0.086
output = 0.859
cache_read = 0.018
cache_write = 0.018

