name = "StepFun Coding Plan (China)"
env = ["STEPFUN_API_KEY"]
npm = "@ai-sdk/openai-compatible"
doc = "https://platform.stepfun.com/docs/zh/step-plan/overview"
api = "https://api.stepfun.com/step_plan/v1"
