base_model = "alibaba/qwen3-32b"
base_model_omit = ["knowledge"]
name = "Qwen/Qwen3-32B"
release_date = "2025-04-30"
last_updated = "2025-11-25"
reasoning = false
structured_output = true
open_weights = false

[cost]
input = 0.14
output = 0.57

[limit]
context = 131000
output = 131000
