base_model = "google/gemini-3.5-flash"
release_date = "2026-06-22"
last_updated = "2026-08-01"
tool_call = false
structured_output = false
reasoning_options = []

[cost]
input = 1.5
output = 9

[limit]
context = 1_000_000
output = 1_000_000

[modalities]
input = ["text", "image"]
