base_model = "alibaba/qwen3-next-80b-a3b-thinking"
structured_output = true
reasoning_options = []

[interleaved]
field = "reasoning_content"

[cost]
input = 0.15
output = 1.2
reasoning = 1.2
cache_read = 0.015
cache_write = 0.18

[limit]
input = 120_000
output = 16_384
