base_model = "openai/gpt-oss-20b"
name = "GPT OSS 20B (Regolo)"
attachment = true
reasoning_options = []

[cost]
input = 0.11645
output = 0.48909

[limit]
output = 131_072

[modalities]
input = ["text", "image"]
