name = "LongCat-2.0"
description = "LongCat-2.0 model"
family = "longcat"
release_date = "2026-06-30"
last_updated = "2026-06-30"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
