name = "Deepseek/Deepseek R1 Turbo"
family = "deepseek"
release_date = "2025-01-30"
last_updated = "2025-01-30"
attachment = false
reasoning = false
tool_call = true
open_weights = false

[cost]
input = 0.7
output = 2.5
cache_read = 0.7
cache_write = 2.5

[limit]
context = 64_000
output = 64_000

[modalities]
input = ["text"]
output = ["text"]
