name = "Holo2 30B A3B"
release_date = "2025-11"
last_updated = "2025-11"
attachment = true
reasoning = true
reasoning_options = []
temperature = true
tool_call = true
structured_output = false
open_weights = true

[cost]
input = 0.399
output = 0.969

[limit]
context = 22_016
output = 16_384

[modalities]
input = ["text", "image"]
output = ["text"]
