name = "Qwen3 Max 2026 01-23"
description = "The snapshot version of the Tongyi Qianwen 3 series Max model is from January 23, 2026. By default, it does not require thinking, but thinking mode can be enabled through the enable_thinking parameter, as detailed in the code example. (After enabling thinking by passing parameters, it becomes: Qwen3-Max-Thinking). This model has a total parameter count exceeding one trillion (1T) and a pre-training data volume of up to 36T Tokens, making it the largest and most powerful reasoning model from Alibaba to date."
release_date = "2026-01-23"
last_updated = "2026-01-23"
attachment = false
reasoning = true
tool_call = true
structured_output = true
open_weights = false

[[reasoning_options]]
type = "toggle"

[[reasoning_options]]
type = "budget_tokens"

[cost]
input = 0.4508
output = 1.8032
cache_read = 0.09016
cache_write = 0.5635

[[cost.tiers]]
tier = { type = "context", size = 32_000 }
input = 0.902
output = 3.608
cache_read = 0.1804
cache_write = 1.1275

[[cost.tiers]]
tier = { type = "context", size = 128_000 }
input = 1.3522
output = 5.4088
cache_read = 0.27044
cache_write = 1.69025

[limit]
context = 262_144
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
