name = "Kwaipilot: KAT-Coder-Pro V1 (OpenRouter)"
family = "kat-coder"
attachment = false
reasoning = false
tool_call = undefined
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = undefined

[cost]
input = 0.21
output = 0.83
cache_read = 0.04

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
