name = "Qwen: Qwen3 8B (OpenRouter)"
family = "qwen"
attachment = false
reasoning = false
tool_call = undefined
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = undefined

[cost]
input = 0.05
output = 0.4
cache_read = 0.05

[limit]
context = 128_000
output = 8_192

[modalities]
input = ["text"]
output = ["text"]
