name = "xAI: Grok 4 Reasoning"
attachment = false
reasoning = true
tool_call = false
temperature = false
knowledge = ""
release_date = ""
last_updated = "2025-08-09"

[cost]
input = 10 # coins per 100 words
output = 10

[limit]
context = 256000
output = 256000

[modalities]
input = ["text"]
output = ["text"]
