name = "databricks-gpt-oss-120b"
description = "GPT OSS 120B is a state-of-the-art, reasoning model with chain-of-thought and adjustable reasoning effort levels built and trained by OpenAI. It is OpenAI's flagship open-weight model that features a 128K token context window. The model is built for high-quality reasoning tasks."
release_date = "2026-01-27"
last_updated = "2026-08-01"
attachment = false
reasoning = true
tool_call = true
structured_output = false
open_weights = false
reasoning_options = []

[cost]
input = 0.15001
output = 0.59997

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
