name = "databricks-gemma-3-12b"
description = "Gemma 3 12B is a state-of-the-art multimodal language model built and trained by Google. The model supports a context length of 128K tokens and can analyze images and text. With support for over 140 languages and optimized for dialogue use cases, Gemma 3 12B is aligned with human preferences for helpfulness and safety. This endpoint is hosted by Databricks."
release_date = "2026-01-27"
last_updated = "2026-08-01"
attachment = true
reasoning = false
tool_call = true
structured_output = false
open_weights = false

[cost]
input = 0.15001
output = 0.50001

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
