name = "Llama 3.3 70B Instruct Turbo"
description = "Meta Llama 3.3 70B Instruct Turbo is an advanced language model optimized for instruction-following tasks with high efficiency and performance."
family = "llama"
release_date = "2025-09-30"
last_updated = "2025-09-30"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 1.144
output = 1.144

[limit]
context = 128_000
input = 128_000
output = 127_000

[modalities]
input = ["text"]
output = ["text"]
