base_model = "google/deep-research-preview-04-2026"
name = "Deep Research Preview (Apr-21-2026)"
attachment = false
temperature = true
tool_call = false
reasoning_options = []

[cost]
input = 0
output = 0

[limit]
context = 131_072
input = 65_536

[modalities]
input = ["text"]
output = ["text"]
