base_model = "inclusionai/ling-2.6-flash"
name = "Ling-2.6-flash"
description = "inclusionAI: Ling-2.6-flash"
release_date = "2026-04-22"
last_updated = "2026-04-22"
attachment = true
reasoning = false
temperature = true
tool_call = true
knowledge = "2025-01-01"
open_weights = false

[cost]
input = 0.1
output = 0.3
cache_read = 0.02

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
