name = "@cf/mistralai/mistral-small-3.1-24b-instruct"
description = "Mistral Small 3.1 24B Instruct is an upgraded variant of Mistral Small 3 (2501), featuring 24 billion parameters with advanced multimodal capabilities. It provides state-of-the-art performance in text-based reasoning and..."
release_date = "2025-03-17"
last_updated = "2026-08-01"
attachment = true
reasoning = false
tool_call = true
structured_output = false
open_weights = false

[cost]
input = 0.351
output = 0.555

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text", "image"]
output = ["text"]
