name = "NVIDIA: Llama 3.1 Nemotron Ultra 253B v1 (OpenRouter)"
family = "nemotron"
attachment = false
reasoning = false
tool_call = false
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = false

[cost]
input = 0.6
output = 1.8

[limit]
context = 128_000
output = 4_096

[modalities]
input = ["text"]
output = ["text"]
