name = "Nous: Hermes 3 405B Instruct (OpenRouter)"
family = "nousresearch"
attachment = false
reasoning = false
tool_call = undefined
temperature = true
release_date = "2026-02-14"
last_updated = "2026-02-14"
open_weights = undefined

[cost]
input = 1
output = 1

[limit]
context = 128_000
output = 16_384

[modalities]
input = ["text"]
output = ["text"]
