# Toggle: thinking.type = enabled|disabled
# https://zenmux.ai/docs/guide/advanced/reasoning.html
base_model = "deepseek/deepseek-v3.2-exp"

[[reasoning_options]]
type = "toggle"

[cost]
input = 0.216
output = 0.328
