name = "Qwen3 VL Embedding"
description = "The Qwen3-VL-Embedding model series are the latest additions to the Qwen family, built upon the recently open-sourced and powerful Qwen3-VL foundation model. Specifically designed for multimodal information retrieval and cross-modal understanding, this suite accepts diverse inputs including text, images, screenshots, and videos, as well as inputs containing a mixture of these modalities."
release_date = "2026-01-08"
last_updated = "2026-01-08"
attachment = true
reasoning = false
temperature = false
tool_call = false
open_weights = false

[limit]
context = 8_192
output = 8_192

[modalities]
input = ["text", "video", "image"]
output = ["text"]
