# Effort: reasoning_effort = low|medium|high
base_model = "google/gemini-2.5-flash-lite"
reasoning_options = [{ type = "effort", values = ["low", "medium", "high"] }]

[interleaved]
field = "reasoning_content"

[cost]
input = 0.085
output = 0.34
cache_read = 0.01

[limit]
output = 65_535

[modalities]
input = ["text", "image"]
