name = "Gemini 2.5 Flash Lite Preview"
description = "Gemini 2.5 Flash Lite Preview is a lightweight AI model developed by Google, optimized for quick responses and efficient processing, making it ideal for tasks requiring minimal latency and resource consumption"
family = "gemini"
release_date = "2025-09-09"
last_updated = "2025-09-09"
attachment = true
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.0975
output = 0.39
cache_read = 0.0975

[limit]
context = 1_000_000
input = 1_000_000
output = 1_048_576

[modalities]
input = ["image", "text"]
output = ["text"]
