name = "Qwen3 Coder"
description = "Alibaba's Qwen 3 Coder is a powerful coding agent."
family = "qwen"
release_date = "2025-09-09"
last_updated = "2025-09-09"
attachment = false
reasoning = false
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 2.6
output = 2.6

[limit]
context = 262_000
input = 262_000
output = 65_536

[modalities]
input = ["text"]
output = ["text"]
