base_model = "meta/llama-3.3-70b-instruct"
description = "A lightweight and ultra-fast variant of Llama 3.3 70B, for use when quick response times are needed most."
attachment = false
structured_output = false

[cost]
input = 0.23
output = 0.4

[limit]
context = 131_072
output = 131_072
