name = "Qwen3.5-35B-A3B"
family = "qwen"
release_date = "2026-03"
last_updated = "2026-03"
attachment = false
reasoning = false
temperature = true
tool_call = true
structured_output = true
open_weights = true
status = "beta"

[cost]
input = 0.00
output = 0.00

[limit]
context = 131_072
input = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
