base_model = "zhipuai/glm-4.7-flash"
name = "GLM 4.7 Flash"
reasoning_options = []

[interleaved]
field = "reasoning_details"

[cost]
input = 0.171925
output = 0.6877
cache_read = 0.013754

[limit]
context = 202_752
output = 16_384
