name = "Qwen/Qwen3 235b A22b Fp8"
family = "qwen"
release_date = "2025-04-28"
last_updated = "2025-04-28"
attachment = false
reasoning = false
tool_call = false
open_weights = false

[cost]
input = 0.2
output = 0.8
cache_read = 0.2
cache_write = 0.2

[limit]
context = 128_000
output = 128_000

[modalities]
input = ["text"]
output = ["text"]
