name = "MiMo V2 Omni"
base_model = "xiaomi/mimo-v2-omni"
release_date = "2026-03-19"
last_updated = "2026-03-19"
reasoning = false
structured_output = false

[cost]
input = 0.4
output = 2
cache_read = 0.08

[limit]
context = 262144
input = 262144
output = 65536

[modalities]
input = [ "text", "image", "video", "audio" ]
output = [ "text" ]

