name = "GPT-5.4 Pro"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = false
release_date = "2026-02"
last_updated = "2026-06"
[cost]
input = 30.9
output = 185.4
[limit]
context = 1050000
output = 128000
[modalities]
input = ["text"]
output = ["text"]
