#!/usr/bin/env bun
// Generates providers/llmtr/models/**.toml for LLMTR's passthrough models.
//
// LLMTR is an OpenAI-compatible gateway that proxies other providers' models, so every
// generated entry uses `base_model` and only declares what is provider-specific: LLMTR's
// price, its served context window, and its reasoning surface.
//
// `reasoning_options` is derived from LLMTR's own per-model `capabilities` array rather
// than the base model's `reasoning` flag:
//   reasoning_effort_<level>  -> [[reasoning_options]] type = "effort"
//   *_toggle                  -> [[reasoning_options]] type = "toggle"
//   neither                   -> reasoning_options = []   (reasons, no verified control)
//
// Source: https://llmtr.com/api/models (public, no auth). Run with: bun llmtr:generate
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs"
import path from "node:path"

const ROOT = path.join(import.meta.dir, "..", "..", "..")
const MODELS = path.join(ROOT, "models")
const OUT = path.join(ROOT, "providers", "llmtr", "models")
const API = "https://llmtr.com/api/models"

// LLMTR `owned_by` -> models.dev base namespace
const NS: Record<string, string> = {
  anthropic: "anthropic", openai: "openai", google: "google", qwen: "alibaba",
  deepseek: "deepseek", zai: "zhipuai", moonshot: "moonshotai", minimax: "minimax",
  mistral: "mistral", perplexity: "perplexity", stepfun: "stepfun", mimo: "xiaomi",
  meta: "meta", nvidia: "nvidia", xai: "xai", cohere: "cohere", tencent: "tencent",
}

// schema order for reasoning effort levels
const EFFORT_ORDER = ["none", "minimal", "low", "medium", "high", "xhigh", "max"]

function findBase(ns: string, model: string): string | undefined {
  const dir = path.join(MODELS, ns)
  if (!existsSync(dir)) return undefined
  const ids = readdirSync(dir).filter((f) => f.endsWith(".toml")).map((f) => f.slice(0, -5))
  const want = [model.toLowerCase(), model.toLowerCase().replaceAll(".", "-")]
  return ids.find((id) => want.includes(id.toLowerCase()))
}

const reasons = (ns: string, id: string) =>
  /(^|\n)\s*reasoning\s*=\s*true/.test(readFileSync(path.join(MODELS, ns, `${id}.toml`), "utf8"))

// LLMTR's API is authoritative for cost, served context, and the reasoning surface, but not
// for how a model is factored. Per sync.md, keep an existing `base_model` pointer and any
// hand-authored `base_model_omit` / `status` instead of clobbering them on re-run.
type Authored = { base_model?: string; base_model_omit?: string[]; status?: string }
function loadAuthored(file: string): Authored {
  if (!existsSync(file)) return {}
  const t = Bun.TOML.parse(readFileSync(file, "utf8")) as Authored
  return { base_model: t.base_model, base_model_omit: t.base_model_omit, status: t.status }
}

// Build the reasoning_options block from LLMTR's per-model capabilities.
// A named provider toggle (e.g. zai_thinking_toggle) is the vendor's documented chat control,
// so it wins over reasoning_effort_* when a model advertises both (verified: GLM-5.2 accepts
// both over chat, but provider.toml documents the GLM family as a toggle). Effort is only
// emitted when it is the model's sole reasoning control.
function reasoningOptions(caps: string[]): string {
  if (caps.some((c) => c.endsWith("_toggle"))) {
    return `\n[[reasoning_options]]\n# API: $.reasoning = true|false (suffix aliases :think|:fast)\ntype = "toggle"\n`
  }
  const efforts = EFFORT_ORDER.filter((l) => caps.includes(`reasoning_effort_${l}`))
  if (efforts.length) {
    const values = efforts.map((v) => `"${v}"`).join(", ")
    return `\n[[reasoning_options]]\n# API: $.reasoning.effort = ${efforts.join("|")} (model suffixes :${efforts.join("|:")} are aliases)\ntype = "effort"\nvalues = [${values}]\n`
  }
  return "" // caller writes `reasoning_options = []`
}

const GENERATED = "# Generated by `bun llmtr:generate`"
const accessed = new Date().toISOString().slice(0, 10)
const list = (await (await fetch(API)).json()).data.data as any[]
const chat = list.filter((m) => (m.supported_operations || []).includes("CHAT_COMPLETIONS"))

const kept = new Set<string>()
// Every slug LLMTR currently lists, generated or not. Entries this run skips (tiered
// pricing, no base match, an owner outside NS) are still served and may be authored by
// hand, so pruning must key off this set rather than off what the run happened to write.
const served = new Set(list.map((m) => `${m.id as string}.toml`))
const skipped = { noNs: [] as string[], noBase: [] as string[], noPrice: [] as string[], authored: [] as string[] }
let queue = chat.map((m) => m.id as string)

async function worker() {
  while (queue.length) {
    const slug = queue.shift()!
    const [owner, ...rest] = slug.split("/")
    const model = rest.join("/")
    const ns = NS[owner]
    if (!ns) { skipped.noNs.push(slug); continue }
    const base = findBase(ns, model)
    if (!base) { skipped.noBase.push(slug); continue }

    const d = (await (await fetch(`${API}/${slug}`)).json()).data.model
    // Only flat per-token text pricing can be expressed as a single cost.input/cost.output.
    // Tiered models price by context size, and a duplicated INPUT_TEXT/OUTPUT_TEXT row is
    // ambiguous — writing either would silently commit a wrong price, so skip both.
    //
    // primaryPricingRows lists one row per (operation, metric): a model served over both
    // /v1/chat/completions and /v1/responses repeats INPUT_TEXT/OUTPUT_TEXT once per
    // operation. This catalog only covers CHAT_COMPLETIONS, so scope the rows to that
    // operation before counting — otherwise the duplicate-row guard below misreads the
    // RESPONSES copy as ambiguity and drops a model LLMTR still serves.
    const rows = (d.primaryPricingRows || []) as { operation: string; metric: string; priceUsd: string }[]
    const chatRows = rows.filter((r) => r.operation === "CHAT_COMPLETIONS")
    const ins = chatRows.filter((r) => r.metric === "INPUT_TEXT")
    const outs = chatRows.filter((r) => r.metric === "OUTPUT_TEXT")
    if (d.pricingSummary?.pricingModel === "tiered" || ins.length > 1 || outs.length > 1) {
      skipped.noPrice.push(slug)
      continue
    }
    const input = ins.length ? Number(ins[0].priceUsd) : undefined
    const output = outs.length ? Number(outs[0].priceUsd) : undefined
    if (input === undefined || output === undefined) { skipped.noPrice.push(slug); continue }

    const caps: string[] = d.capabilities || []
    const block = reasons(ns, base) ? reasoningOptions(caps) : ""
    const empty = reasons(ns, base) && !block

    const file = path.join(OUT, `${slug}.toml`)
    // A file this generator did not write is hand-authored: it carries measurements and
    // rationale (audio pricing units, a reasoning-token price, a deliberately inherited
    // context) that LLMTR's API cannot express. Regenerating it would silently drop that.
    if (existsSync(file) && !readFileSync(file, "utf8").startsWith(GENERATED)) {
      skipped.authored.push(slug)
      continue
    }
    const authored = loadAuthored(file)

    let t = `${GENERATED} from ${API} (accessed ${accessed}).\n`
    t += `# reasoning_options reflect LLMTR's per-model capabilities, not the base model's flag.\n`
    t += `base_model = "${authored.base_model ?? `${ns}/${base}`}"\n`
    if (authored.base_model_omit) t += `base_model_omit = [${authored.base_model_omit.map((v) => `"${v}"`).join(", ")}]\n`
    if (authored.status) t += `status = "${authored.status}"\n`
    if (empty) t += `reasoning_options = []\n`
    t += `\n[cost]\ninput = ${input}\noutput = ${output}\n`
    const ctx = Number(d.contextWindow)
    if (Number.isFinite(ctx) && ctx > 0) t += `\n[limit]\ncontext = ${ctx.toLocaleString("en-US").replaceAll(",", "_")}\n`
    t += block

    mkdirSync(path.dirname(file), { recursive: true })
    writeFileSync(file, t)
    kept.add(`${slug}.toml`)
  }
}
await Promise.all(Array.from({ length: 8 }, worker))

// Prune passthrough entries LLMTR no longer serves (first-party llmtr/* models live at the
// top level of OUT and are hand-authored, so only nested <owner>/<model>.toml are managed).
// Skipped-but-served models keep their files: a tiered price or a missing base model is a
// gap in this generator, not a retirement.
function walk(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)],
  )
}
const removed: string[] = []
for (const file of walk(OUT)) {
  const rel = path.relative(OUT, file).replaceAll("\\", "/")
  if (!rel.includes("/") || !rel.endsWith(".toml")) continue
  if (served.has(rel)) continue
  rmSync(file)
  removed.push(rel)
}

console.log("written:", kept.size)
console.log("removed (no longer served):", removed.length, removed.join(", "))
console.log("skipped (hand-authored):", skipped.authored.length, skipped.authored.join(", "))
console.log("skipped (no base namespace):", skipped.noNs.length)
console.log("skipped (no matching base):", skipped.noBase.length)
console.log("skipped (tiered/no flat price):", skipped.noPrice.length)
