name = "Qwen 3 235B A22B Thinking (2507)"
family = "qwen"
release_date = "2025-07-23"
last_updated = "2025-11-25"
attachment = false
reasoning = true
tool_call = true
temperature = true
open_weights = true

[cost]
input = 0.23
output = 2.30
cache_read = 0.20

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
