name = "qwen3-vl-8b-instruct"
description = "The Instruct version of the 8B Dense model in the Qwen3-VL series requires less GPU memory and provides comprehensively upgraded image/video understanding, support for extremely long contexts like lengthy videos and documents, spatial awareness, and object recognition capabilities, making it suitable for tackling complex real-world tasks."
release_date = "2025-10-14"
last_updated = "2026-08-01"
attachment = true
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.117
output = 0.455

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["image", "text", "video"]
output = ["text"]
