name = "qwen3-max-2025-09-23"
description = "The Qwen 3 series Max model has undergone specialized upgrades in agent programming and tool invocation compared to the preview version. The officially released model this time has achieved state-of-the-art (SOTA) performance in its field and is better suited to meet the demands of agents operating in more complex scenarios.This version is a snapshot as of September 23, 2025."
release_date = "2025-09-23"
last_updated = "2026-08-01"
attachment = false
reasoning = false
tool_call = true
structured_output = true
open_weights = false

[cost]
input = 0.78
output = 3.9

[limit]
context = 262_144
output = 262_144

[modalities]
input = ["text"]
output = ["text"]
