name = "Qwen3.7-Max"
description = "Qwen3.7-Max model"
family = "qwen3.7-max"
release_date = "2026-05-22"
last_updated = "2026-05-22"
attachment = false
reasoning = true
temperature = true
tool_call = true
open_weights = false

[limit]
context = 1_000_000
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
