base_model = "deepseek/deepseek-r1"
temperature = true
tool_call = true
attachment = false
reasoning_options = []
reasoning = true
structured_output = true

[cost]
input = 0.7
output = 2.5

[limit]
context = 64_000
output = 16_000
