name = "Hermes 4 405B"
attachment = false
reasoning = true
tool_call = true
structured_output = false
temperature = true
knowledge = "2024-03"
release_date = "2025-08-27"
last_updated = "2026-01-27"
open_weights = true

[cost]
input = 1.19
output = 4.76

[limit]
context = 128000
input = 128000
output = 16384

[modalities]
input = ["text"]
output = ["text"]
