name = "Qwen3 Coder 480B A35B Instruct"
attachment = false
reasoning = false
tool_call = true
structured_output = true
temperature = true
knowledge = "2024-01"
release_date = "2025-07-22"
last_updated = "2026-01-27"
open_weights = true

[cost]
input = 0.59
output = 2.38

[limit]
context = 262144
input = 262144
output = 65536

[modalities]
input = ["text"]
output = ["text"]
