name = "Agnes 2.5 Flash"
description = "Sapiens AI: Agnes 2.5 Flash"
release_date = "2026-08-10"
last_updated = "2026-08-10"
attachment = true
reasoning = true
temperature = true
tool_call = true
knowledge = "2025-01-01"
open_weights = false

[limit]
context = 524_288
output = 524_288

[modalities]
input = ["text", "image"]
output = ["text"]
