name = "Codex Mini"
family = "gpt-codex-mini"
release_date = "2025-05-16"
last_updated = "2025-05-16"
attachment = true
reasoning = true
temperature = false
tool_call = true
knowledge = "2024-04"
open_weights = false

[cost]
input = 1.5075
output = 6.03
cache_read = 0.376875

[limit]
context = 200_000
output = 100_000

[modalities]
input = ["text"]
output = ["text"]

