base_model = "openai/gpt-oss-120b"
description = "OpenAI's gpt-oss-120b is a powerful open-weight Large Language Model (LLM) designed for advanced chain-of-thought reasoning, agentic workflows, and complex tool-calling."
reasoning = false

[cost]
input = 0.15
output = 0.75
