base_model = "openai/gpt-5-codex"
temperature = false
structured_output = true
tool_call = true
reasoning_options = [{ type = "effort", values = ["low", "medium", "high"] }]
reasoning = true
attachment = true

[cost]
input = 1.25
output = 10
cache_read = 0.125
