# https://deepinfra.com/nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning
name = "Nemotron 3 Nano Omni 30B A3B Reasoning"
family = "nemotron"
release_date = "2026-04-01"
last_updated = "2026-04-01"
attachment = true
reasoning = true
structured_output = true
temperature = true
tool_call = true
knowledge = "2025-04"
open_weights = true

[cost]
input = 0.20
output = 0.80

[limit]
context = 262_144
output = 81_920

[modalities]
input = ["text", "image", "video", "audio"]
output = ["text"]
